### ISSUE TITLE
Still accepting entries / PR?

### ISSUE THREAD

**Issue by mistermantas** [agarrharr/awesome-static-website-services#59]
Seems like inactive repo // cc @agarrharr

**Comment by agarrharr** [comment]
It's still active, I've just been a little busy IRL. I could use some help with reviewing PRs and issues though.

**Comment by mistermantas** [comment]
Well, thing is I wanna add my PR to the project, but I was a bit hesitant with the other open ones. If I were to do that, would cstate/cstate be a good contender? :)

**Comment by agarrharr** [comment]
So, it looks like cstate is a static site that shows the status of any website correct? This *probably* isn't a good fit for this list because it focuses on services specifically for static sites.

**Comment by mistermantas** [comment]
it’s a tool like any other. (especially if you take into account that stuff like soundcloud is on the list.)

should i make a PR or move on? 🤔

**Comment by agarrharr** [comment]
True. This list focuses more on things that you can embed on the page to extend the functionality of the site. I think the only exception is "Functions as a Service", but that still extends the functionality. It's just a bit more custom.

It might be better on this list: https://github.com/lvwzhen/tools

**Comment by agarrharr** [comment]
By the way, it does look awesome! I just want to limit the scope of this list.

**Comment by mistermantas** [comment]
Thanks for the alternative and thanks for your time! ♥️
