### ISSUE TITLE
no explanation for "FormAssembly.com" in Normal forms section

### ISSUE THREAD

**Issue by Nikronic** [agarrharr/awesome-static-website-services#61]
Hello
Actually, it is not a big deal, just some formatting. There is **no description** for **FormAssembly** in [Normal Forms](https://github.com/agarrharr/awesome-static-website-services#normal-forms) section.

**Comment by waldyrious** [comment]
I went to look for who had introduced that line, and turns out it was @agarrharr himself in a7c016273 😄

@Nikronic what would you suggest as a description for that link?

**Comment by Nikronic** [comment]
Awesome but expensive forms!
Actually, I am not a web developer, so I do not know what should be highlighted in the description.

**Comment by waldyrious** [comment]
From the text in the website, and after removing a ton of marketing speak, I came up with the following description using their words:

> a web form creation and integration solution for enterprises, including integration with Salesforce.

How does this sound, @Nikronic / @agarrharr?

(Personally, I'm not sure they qualify as awesome, but that's a judgment I'll leave @agarrharr to make.)

**Comment by waldyrious** [comment]
@Nikronic why did you close this?

**Comment by Nikronic** [comment]
Because adding a simple description does not take **two** month. And after all, I opened this issue in 1 Novemeber for the first time and I closed issue a week ago because I thought this repository no longer maintenance. And exactly after I closed issue, the owner opened it again! WTF!
And now I am sure.

**Comment by agarrharr** [comment]
I finally got around to this. Sorry for the delay. I wanted to keep the issue open as a reminder.
