### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/awesome-static-website-services#65]
I haven't had the time/interest to work on this lately. If anyone else is interested in working on this, let me know.

**Comment by schalkventer** [comment]
I'm very passionate about static sites and use the JAMStack in 95% of the work that I do. I'd be more than happy to help out.

**Comment by agarrharr** [comment]
That's great! I added ya'll as collaborators. If you could respond to issues and pull requests and make sure the pull requests follow the contribution guidelines.

**Comment by iamtekeste** [comment]
Let me know if you still need help maintaining this repo @agarrharr . I am up for the task!

**Comment by jtagcat** [comment]
I'm quite interested in awesome-* repos, especially since this isn't a very big one, I can keep an eye on every notification.
