### ISSUE TITLE
Add static website generator

### ISSUE THREAD

**Issue by azbarcea** [agarrharr/awesome-static-website-services#75]
Is there a reason why Jekyll and Pelican are missing from this awesome page ?

**Comment by knayan1** [comment]
Please add and create PR

**Comment by b-long** [comment]
Eager to accept PRs over at https://github.com/b-long/awesome-static-hosting-and-cms .  Of course, I'll defer to @agarrharr

**Comment by agarrharr** [comment]
It because this isn’t a list about all things around static websites. It just about services that you can use on a static site.

**Comment by azbarcea** [comment]
So @agarrharr ... would you consider approving a PR with static site generators?

**Comment by azbarcea** [comment]
> Eager to accept PRs over at https://github.com/b-long/awesome-static-hosting-and-cms . Of course, I'll defer to @agarrharr

@b-long, we can also explore them in your repo. Actually, you gave me the idea to google:
```
jekyll pelican site:github.com inurl:awesome -inurl:jekyll -inurl:pelican
```
So, is not a bad idea to consolidate them somewhere.

**Comment by agarrharr** [comment]
awesome-static-hosting-and-cms is probably a better fit.
